"""added lieks to reviews and genre to albums

Revision ID: 9afad348c82e
Revises: 9c37908fcc5b
Create Date: 2023-05-10 10:16:36.670819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afad348c82e'
down_revision = '9c37908fcc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
